apiVersion: v1
kind: page
spec:
  id: n_N5mEy
  title: Contact
  display: shell
  content:
    - component: PageRow
      name: pageRow
      children:
        - component: Form
          name: form
          children:
            - component: PageRow
              name: pageRow1
              children:
                - component: TextField
                  name: textField
                  props:
                    fullWidth: true
                    label: Name
                    isRequired: true
